### ISSUE TITLE
How to use the token in other workspace requests?

### ISSUE THREAD

**Issue by rose-a** [PaddeK/insomnia-plugin-workspace-jwt#2]
Hi,

I've set up my auth request and the filter as documented (and it displays the token after setup), but I don't get how I can set the token from the "Authorization request" as the Bearer token in other requests.

Could somebody please point that out to me?

**Comment by adamkerz** [comment]
PR for readme update to address this: https://github.com/PaddeK/insomnia-plugin-workspace-jwt/pull/5

**Comment by PaddeK** [comment]
Since the PR is merged (thx to @adamkerz) this should be solved now.
