### ISSUE TITLE
Respect Authorization Token type

### ISSUE THREAD

**Issue by abbottdev** [PaddeK/insomnia-plugin-workspace-jwt#3]
Insomnia allows the Token prefix to be customised for Bearer/JWT auth as below:
![image](https://user-images.githubusercontent.com/3226335/157472253-4804385a-08b3-48ab-999c-c79fdbca6b35.png)

It would be great if this plugin could either respect, or, add a configuration option to allow the user to specify the token type, as it's not requried to always be `Bearer` (hence the option in Insomnia.)

**Comment by mnogokotin** [comment]
yep, my api not working with bearer, but with JWT

**Comment by adamkerz** [comment]
Looks fairly easy to implement a new store setting for auth prefix. I might get a chance next week. For now, I've just edited the code: `Insomnia\data\plugins\insomnia-plugin-workspace-jwt\src\RequestHook.js:22` and did `Tools -> Reload plugins`

**Comment by PaddeK** [comment]
Beginning with v1.1.1 you can use environment variable `WORKSPACE-JWT-TOKEN-PREFIX` to change the prefix.
Thanks for the suggestion!

**Comment by adamkerz** [comment]
Wooo, thank you very much!

**Comment by abbottdev** [comment]
@PaddeK sorry only just got around to using this but it's working fantasically. Thank you so much! ❤️
